stages:
  - Test
  - Build
  - Deploy

variables:
  DOCKER_IMAGE_VERSION: 19.03.13-git
  DOCKER_SERVICE_VERSION: 19-dind

default:
  image: docker:$DOCKER_IMAGE_VERSION
  services:
    - docker:$DOCKER_SERVICE_VERSION



testing:
  script: echo "write unit test to make this section necessary"
  stage: Test

building:
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  tags:
    - docker
  script: 
    - docker build -t $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  stage: Build

deployment:
  script: echo "configure heroku to finish this section"
  stage: Deploy